-- 회원제 게시판 프로젝트
CREATE TABLE TBL_USER(
   USER_NUMBER NUMBER,
   USER_ID VARCHAR2(100) NOT NULL UNIQUE,
   USER_PW VARCHAR2(100) NOT NULL,
   USER_NAME VARCHAR2(100) NOT NULL,
   USER_PHONE VARCHAR2(100) NOT NULL UNIQUE,
   USER_BIRTH DATE,
   USER_RECOMMENDERNUMBER NUMBER,
   CONSTRAINT PK_USER PRIMARY KEY(USER_NUMBER),
   CONSTRAINT FK_USER FOREIGN KEY(USER_RECOMMENDERNUMBER)
   REFERENCES TBL_USER(USER_NUMBER) 
);

-- 프로젝트 전체에 스퀀스 하나만
CREATE SEQUENCE SEQ_PRO;

INSERT INTO TBL_USER
(USER_NUMBER, USER_ID, USER_PW, USER_NAME, USER_PHONE, USER_BIRTH, USER_RECOMMENDERNUMBER)
VALUES(SEQ_PRO.NEXTVAL, 'rkfka', '1234', '유가람', '010-1234-5678', '2000-11-28', NULL);

-- 중복 검사 쿼리문
SELECT COUNT(USER_ID)  FROM TBL_USER
WHERE USER_ID = 'rkfka';

SELECT * FROM TBL_USER;

UPDATE HR.TBL_USER
SET USER_NUMBER=0, USER_ID='', USER_PW='', USER_NAME='', USER_BIRTH='', USER_RECOMMENDERNUMBER=0
WHERE USER_PHONE='';

UPDATE TBL_USER 
SET USER_PW = 0
WHERE USER_PHONE = 0;

DELETE FROM HR.TBL_USER
WHERE USER_NUMBER='';

SELECT * FROM TBL_USER WHERE USER_NUMBER = '';